"""Design tokens for KTV Player."""

FONT_XS = 10
FONT_SM = 12
FONT_MD = 14
FONT_LG = 16
FONT_XL = 18
FONT_XXL = 24
FONT_XXXL = 32

SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 16
SPACING_LG = 24
SPACING_XL = 32

BORDER_RADIUS_SM = 4
BORDER_RADIUS_MD = 8
BORDER_RADIUS_LG = 12
BORDER_RADIUS_XL = 16
BORDER_RADIUS_FULL = 9999

ICON_SM = 16
ICON_MD = 20
ICON_LG = 24
ICON_XL = 32

ANIMATION_FAST = 150
ANIMATION_NORMAL = 250
ANIMATION_SLOW = 350

# Aliases
SPACE_XS = SPACING_XS
SPACE_SM = SPACING_SM
SPACE_MD = SPACING_MD
SPACE_LG = SPACING_LG
SPACE_XL = SPACING_XL

RADIUS_SM = BORDER_RADIUS_SM
RADIUS_MD = BORDER_RADIUS_MD
RADIUS_LG = BORDER_RADIUS_LG
RADIUS_XL = BORDER_RADIUS_XL
RADIUS_FULL = BORDER_RADIUS_FULL
